{{- if .Values.persistence.workspace.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cognition.fullname" . }}-workspace
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "cognition.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.workspace.accessMode }}
  storageClassName: {{ .Values.persistence.workspace.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
{{- end }}
